// Meu Treino Pro v5.4 — substituição por equivalência biomecânica
(function(){
 const ENGINE_VERSION='5.4';
 function ls(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}}
 function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
 function clean(s=''){return String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
 function availableIds(){try{return new Set(getEquipmentCatalog().filter(e=>e.available!==false).map(e=>e.id))}catch(e){return new Set()}}
 function importedLibrary(){const x=ls('importedExerciseLibraryV52',[]);return Array.isArray(x)?x:[]}
 const MUSCLE_ALIASES={biceps:['biceps'],triceps:['triceps'],peito:['peito','peitoral','pectorais'],costas:['costas','dorsais','dorsal','romboides'],ombros:['ombros','ombro','deltoide','deltoides'],quadriceps:['quadriceps'],posteriores:['posteriores','posterior de coxa','posteriores de coxa','isquiotibiais'],gluteos:['gluteos','gluteo'],adutores:['adutores','adutor'],panturrilhas:['panturrilhas','panturrilha'],core:['core','abdomen','abdominal']};
 function canonicalMuscle(text=''){const first=clean(text).split(/[•,\/]+/)[0].trim();for(const [key,words] of Object.entries(MUSCLE_ALIASES))if(words.some(w=>first.includes(w)))return key;return first}
 function movementPattern(name='',muscle=''){
  const n=clean(name),m=canonicalMuscle(muscle);
  if(/voador|peck|crucifixo/.test(n))return 'chest_fly';
  if(/supino|chest press|press peito/.test(n))return 'chest_press';
  if(/puxada alta|pulldown|barra fixa/.test(n))return 'vertical_pull';
  if(/remada/.test(n))return 'horizontal_row';
  if(/rosca scott|rosca direta|rosca alternada|rosca na polia/.test(n))return 'elbow_flexion_supinated';
  if(/rosca martelo/.test(n))return 'elbow_flexion_neutral';
  if(/triceps.*corda|triceps.*polia|pushdown/.test(n))return 'elbow_extension_down';
  if(/triceps frances|triceps.*cabeca|overhead/.test(n))return 'elbow_extension_overhead';
  if(/extensora|extensao de joelho/.test(n))return 'knee_extension';
  if(/flexora|flexao de joelho/.test(n))return 'knee_flexion';
  if(/abdutora|abducao/.test(n))return 'hip_abduction';
  if(/adutora|aducao/.test(n))return 'hip_adduction';
  if(/agachamento|goblet/.test(n))return 'squat';
  if(/terra romeno|stiff/.test(n))return 'hip_hinge';
  if(/desenvolvimento|shoulder press/.test(n))return 'vertical_press';
  if(/elevacao lateral/.test(n))return 'shoulder_abduction';
  if(/prancha/.test(n))return 'core_anti_extension';
  if(/abdominal|crunch/.test(n))return 'trunk_flexion';
  if(/esteira|caminhada/.test(n))return 'cardio_walk';
  return m?`other_${m}`:'unknown';
 }
 function normalizeExercise(e,source='base'){const x={name:String(e.name||'Exercício'),muscle:String(e.muscle||'A definir'),equipment:Array.isArray(e.equipment)?e.equipment:[],group:String(e.group||'custom'),target:String(e.target||'2 × 10–12'),level:String(e.level||'Adaptação'),desc:String(e.desc||''),video:e.video||('https://www.youtube.com/results?search_query='+encodeURIComponent(String(e.name||'exercicio')+' execução correta')),_source:source};x.pattern=e.pattern||movementPattern(x.name,x.muscle);return x}
 function extraVariants(){return [
  {name:'Rosca Scott na MS-8000',muscle:'Bíceps',equipment:['uplift_ms8000'],group:'pull',target:'2 × 10–12',desc:'Flexão do cotovelo com pegada supinada e braços apoiados.'},
  {name:'Rosca direta na polia baixa da MS-8000',muscle:'Bíceps • antebraços',equipment:['uplift_ms8000'],group:'pull',target:'2 × 10–12',desc:'Flexão do cotovelo com pegada supinada na polia baixa.'},
  {name:'Rosca alternada com halteres',muscle:'Bíceps',equipment:['dumbbells'],group:'pull',target:'2 × 10–12',desc:'Flexão alternada do cotovelo com pegada supinada.'},
  {name:'Rosca martelo com halteres',muscle:'Bíceps • braquial • antebraços',equipment:['dumbbells'],group:'pull',target:'2 × 10–12',desc:'Flexão do cotovelo com pegada neutra.'},
  {name:'Tríceps na corda na MS-8000',muscle:'Tríceps',equipment:['uplift_ms8000'],group:'push',target:'2 × 10–12',desc:'Extensão do cotovelo na polia alta.'},
  {name:'Tríceps francês com halter',muscle:'Tríceps',equipment:['dumbbells'],group:'push',target:'2 × 10–12',desc:'Extensão do cotovelo acima da cabeça.'}
 ]}
 function exercisePool(){const have=availableIds(),imported=importedLibrary().map(e=>normalizeExercise(e,'imported')),base=(typeof v51ExerciseLibrary!=='undefined'?v51ExerciseLibrary:[]).map(e=>normalizeExercise(e,'base')),variants=extraVariants().map(e=>normalizeExercise(e,'variant')),seen=new Set(),all=[];[...imported,...variants,...base].filter(e=>e.equipment.every(id=>have.has(id))).forEach(e=>{const key=clean(e.name);if(!seen.has(key)){seen.add(key);all.push(e)}});return all}
 function take(pool,group,n){return pool.filter(e=>e.group===group).slice(0,n)}
 function generate(){const pool=exercisePool(),cardio=take(pool,'cardio',1),core=take(pool,'core',2),A=[...cardio,...take(pool,'push',5),...(core[0]?[core[0]]:[])],B=[...cardio,...take(pool,'pull',5),...(core[1]?[core[1]]:core[0]?[core[0]]:[])],C=[...cardio,...take(pool,'legs',6),...(core[0]?[core[0]]:[])],data={version:ENGINE_VERSION,generatedAt:new Date().toISOString(),A,B,C};save('activeWorkoutsV53',data);save('generatedWorkoutsV5',{A,B,C});return data}
 function current(){const d=ls('activeWorkoutsV53',null);return d&&d.version===ENGINE_VERSION?d:generate()}
 function summary(d){return `A: ${d.A.length} • B: ${d.B.length} • C: ${d.C.length}`}
 window.recalculateWorkouts=function(silent=false){const data=generate();if(typeof renderGeneratedNotice==='function')renderGeneratedNotice();buildWorkout();if(!silent)alert(`Treinos atualizados. ${summary(data)}.`);return data};
 function selectedDayExercises(){const day=document.getElementById('day')?.value||'A';return current()[day]||[]}
 function alternatives(ex){const p=ex.pattern||movementPattern(ex.name,ex.muscle),m=canonicalMuscle(ex.muscle);return exercisePool().filter(x=>clean(x.name)!==clean(ex.name)&&canonicalMuscle(x.muscle)===m&&(x.pattern||movementPattern(x.name,x.muscle))===p).slice(0,20)}
 window.openDynamicSub=function(idx){const day=document.getElementById('day')?.value||'A',ex=current()[day]?.[idx];if(!ex)return;const opts=alternatives(ex),p=ex.pattern||movementPattern(ex.name,ex.muscle),modal=document.getElementById('subModal'),title=document.getElementById('subCurrent'),host=document.getElementById('subOptions');title.textContent=`Substituir ${ex.name} — somente equivalentes`;host.innerHTML=opts.length?opts.map((a,i)=>`<div class="altcard"><b>${a.name}</b><div class="accent">Equivalente • ${canonicalMuscle(a.muscle)}</div><div class="muted">${a.target} • mesmo padrão de movimento</div><p>${a.desc||''}</p><button class="primary" onclick="applyDynamicSub(${idx},${i})">Substituir por este</button></div>`).join(''):`<div class="card notice"><b>Não há substituto biomecanicamente equivalente cadastrado.</b><p class="muted">O app não oferecerá apenas outro exercício do mesmo músculo. Padrão exigido: ${p}.</p></div>`;window.__dynamicAlternatives=opts;modal.classList.remove('hide')};
 window.applyDynamicSub=function(idx,optIdx){const day=document.getElementById('day')?.value||'A',data=current(),old=data[day]?.[idx],alt=window.__dynamicAlternatives?.[optIdx];if(!old||!alt)return;const same=canonicalMuscle(old.muscle)===canonicalMuscle(alt.muscle)&&(old.pattern||movementPattern(old.name,old.muscle))===(alt.pattern||movementPattern(alt.name,alt.muscle));if(!same)return;data[day][idx]=alt;data.generatedAt=new Date().toISOString();save('activeWorkoutsV53',data);save('generatedWorkoutsV5',{A:data.A,B:data.B,C:data.C});document.getElementById('subModal')?.classList.add('hide');buildWorkout()};
 window.buildWorkout=function(){const day=document.getElementById('day')?.value||'A',phase=document.getElementById('phase')?.value||'2',host=document.getElementById('workoutList');if(!host)return;host.innerHTML='';const list=current()[day]||[];if(!list.length){host.innerHTML='<div class="card notice"><b>Nenhum treino compatível.</b><p class="muted">Ative ou importe equipamentos e toque em Recalcular treinos.</p></div>';return}list.forEach((e,idx)=>{const card=document.createElement('article');card.className='card exercise';let setCount=(e.target.match(/^(\d+)/)||[])[1];setCount=setCount?+setCount:0;if(phase==='1'&&setCount>2)setCount=2;card.innerHTML=`<div class="exhead"><div><h3>${idx+1}. ${e.name}</h3><div class="accent">${e.muscle} • ${e.target}</div></div><a class="iconbtn" target="_blank" rel="noopener" href="${e.video}">▶</a></div><p>${e.desc||''}</p><button class="subbtn" onclick="openDynamicSub(${idx})">⇄ Substituir por equivalente</button>${setCount?`<div class="sets">${Array.from({length:setCount},(_,s)=>`<div class="setrow"><b>S${s+1}</b><input inputmode="decimal" type="number" step="0.5" placeholder="kg" data-ex="${idx}" data-set="${s}" data-k="kg"><input inputmode="numeric" type="number" placeholder="reps" data-ex="${idx}" data-set="${s}" data-k="reps"><input inputmode="decimal" type="number" min="1" max="10" step="0.5" placeholder="RPE" data-ex="${idx}" data-set="${s}" data-k="rpe"><button class="done" onclick="completeSet(this,${idx},${s})">✓</button></div>`).join('')}</div>`:`<label>Tempo realizado <input type="number" placeholder="min/seg" data-ex="${idx}" data-set="0" data-k="time"></label>`}`;host.appendChild(card)});const box=document.getElementById('generatedNotice');if(box){box.classList.remove('hide');box.innerHTML=`<b>Treino ativo baseado nos equipamentos</b><div class="muted">${summary(current())}. Substituições exigem mesmo músculo principal e mesmo padrão de movimento.</div>`}};
 window.completeSet=function(btn,ex,setn){if(!activeSession)startSession();const e=selectedDayExercises()[ex];if(!e)return;const row=btn.closest('.setrow'),kg=+(row.querySelector('[data-k=kg]').value||0),reps=+(row.querySelector('[data-k=reps]').value||0),rpe=+(row.querySelector('[data-k=rpe]').value||0),rec={exercise:e.name,exIndex:ex,set:setn+1,kg,reps,rpe,ts:new Date().toISOString(),hr:currentHR};activeSession.sets=activeSession.sets.filter(x=>!(x.exIndex===ex&&x.set===setn+1));activeSession.sets.push(rec);btn.classList.add('ok');btn.textContent='✓';startRest(75)};
 const oldToggle=window.toggleEquipment;window.toggleEquipment=function(id,on){oldToggle(id,on);recalculateWorkouts(true)};const oldDelete=window.deleteEquipment;window.deleteEquipment=function(id){const before=getEquipmentCatalog().length;oldDelete(id);if(getEquipmentCatalog().length!==before)recalculateWorkouts(true)};const oldRestore=window.restoreDefaultEquipment;window.restoreDefaultEquipment=function(){const before=JSON.stringify(getEquipmentCatalog());oldRestore();if(JSON.stringify(getEquipmentCatalog())!==before)recalculateWorkouts(true)};const oldSave=window.saveEquipment;window.saveEquipment=function(){oldSave();recalculateWorkouts(true)};
 document.addEventListener('DOMContentLoaded',()=>{document.getElementById('day')?.addEventListener('change',buildWorkout);document.getElementById('phase')?.addEventListener('change',buildWorkout);recalculateWorkouts(true);setTimeout(()=>{const btn=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Recalcular treinos'));if(btn)btn.onclick=()=>recalculateWorkouts(false)},0)});
 if(typeof window.importEquipmentFile==='function'){const oldImport=window.importEquipmentFile;window.importEquipmentFile=async function(ev){await oldImport(ev);recalculateWorkouts(true)}}
})();